import type { Character } from '../types';
export const characters: Character[] = [{ id: 'oikawa', name: '及川', color: '#8bbbd2', emoji: '🏐', line: '生日快樂，今天的好運都要接住喔！' }, { id: 'bokuto', name: '木兔', color: '#e9a165', emoji: '🦉', line: 'HEY HEY HEY！' }, { id: 'kuroo', name: '黑尾', color: '#d7a8bd', emoji: '🐈‍⬛', line: '運氣不錯嘛。' }, { id: 'bakugo', name: '爆豪', color: '#f1b25d', emoji: '🔥', line: '喂！抽到了啦！' }, { id: 'todoroki', name: '轟', color: '#a6d3d4', emoji: '❄️', line: '生日快樂。' }, { id: 'usagi', name: '烏薩琪', color: '#f3c2c4', emoji: '🐰', line: '呀哈～' }];
export const fixedFirstRoundCharacterIds = ['oikawa', 'bokuto', 'kuroo', 'bakugo', 'todoroki', 'usagi'] as const;
export type CharacterSkill = { id: string; characterId: string; title: string; message: string; autoRevealCount: number };
export const firstAwakeningThreshold = 3;
export const characterSkills: CharacterSkill[] = [{ id: 'oikawa-serve', characterId: 'oikawa', title: '及川的幸運發球', message: '好運發球！接下來的驚喜一起接住吧！', autoRevealCount: 2 }, { id: 'bokuto-cheer', characterId: 'bokuto', title: '木兔的生日歡呼', message: 'HEY HEY HEY！驚喜連發！', autoRevealCount: 2 }, { id: 'kuroo-trick', characterId: 'kuroo', title: '黑尾的幸運攔網', message: '把好運攔下來，通通送給你。', autoRevealCount: 2 }, { id: 'bakugo-burst', characterId: 'bakugo', title: '爆豪的全力爆發', message: '這波好運給我一路衝到底！', autoRevealCount: 2 }, { id: 'todoroki-balance', characterId: 'todoroki', title: '轟的雙倍祝福', message: '冷靜收下這份生日驚喜。', autoRevealCount: 2 }, { id: 'usagi-hop', characterId: 'usagi', title: '烏薩琪的蹦蹦好運', message: '呀哈～驚喜兔兔跳出來！', autoRevealCount: 2 }];
export const createPrizeCharacterAssignments = (extras: string[]) => { const pool = [...fixedFirstRoundCharacterIds.flatMap((id) => Array(8).fill(id)), ...extras]; for (let i = pool.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [pool[i], pool[j]] = [pool[j], pool[i]]; } return Object.fromEntries(pool.map((characterId, index) => [index + 1, characterId])); };
export const getCharacterSkill = (id: string) => characterSkills.find((skill) => skill.characterId === id);
export const getRoundForPrize = (prizeId: number): 1 | 2 => prizeId <= 12 ? 1 : 2;
